version: '1'

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      ports:
      - "5000:5000"
      depends_on:
      - client
  client:
    build:
      content: .
      dockerfile: ./client/Dockerfile