version: '2'

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - client
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile