version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5555:5432"
    volumes:
     - db:/var/lib/postgresql/data
volumes:
  db: 

# version: '2'  

# services:
#   server:
#     build:
#       context: .
#       dockerfile: ./server/Dockerfile
#     ports:
#       - "5000:5000"
#     depends_on:
#       - client
#   client:
#     build:
#       context: .
#       dockerfile: ./client/Dockerfile


