# Generated by Django 5.0.1 on 2024-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'unique_together': {('uid', 'year')},
            },
        ),
    ]
