# Generated by Django 5.0.1 on 2024-01-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='year',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
